export const CONFIG = {
  API_BASE: 'http://localhost:3000',
  API_INVOICES_PATH: '/api/tampermonkey/invoices',
  API_PERIODS_PATH: '/api/tampermonkey/periods',
  API_REPORT_STATUS_PATH: '/api/tampermonkey/report-status',

  API_STATUS: 'all',

  SEND_RECEIVER_AS_BASE10_WHEN_ENDS_001: true,
  RECEIVER_RUC_OVERRIDE: '',

  DEFAULT_VIEW_FILTER: 'missing',

  HIDE_WHEN_XML_IS_AVAILABLE: false,

  MARK_UNKNOWN_ROWS: false,

  APPLY_INTERVAL_MS: 2500,
  OBSERVER_DEBOUNCE_MS: 350,

  REFRESH_AFTER_MANUAL_CONSULTAR_MS: [1500, 4000, 8000],

  REFRESH_AFTER_DOWNLOAD_MS: [3000, 8000, 15000],

  AUTO_DOWNLOAD_XML: true,
  AUTO_DOWNLOAD_PDF: false,
  DOWNLOAD_DELAY_MS: 5500,
  MAX_BATCH_DOWNLOADS_PER_PAGE: 200,

  PAGINATION_DELAY_MS: 4500,
  PAGE_AFTER_QUEUE_DELAY_MS: 2500,
  MAX_PAGES_PER_BATCH: 30,

  HIDE_MONTHS_USING_API: true,
  NEVER_HIDE_SELECTED_MONTH: true
};
